name: Me.reasonswhy.presents
version: ${project.version}
main: present.me.reasonswhy.presents.Me.reasonswhy.presents
api-version: 1.16
authors: [27Reasonswhy]
description: Present Plugiin 1.16.4
commands:
  present:
    description: give Present!

